#A simple plugin to handle player transactions to other player.

#Input amount range. (Whole numbers only!)
#Min can't be smaller than 1.
#Max can't be 10 billions or larger, because it may introduce unwanted errors.
Min: 10
Max: 1000000

#Log the transaction to console.
Log: true